/// <reference lib="webworker" />
import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching'
import { initializeApp } from 'firebase/app'
import { getMessaging, onBackgroundMessage } from 'firebase/messaging/sw'

declare const self: any

cleanupOutdatedCaches()

// Precache list generated by workbox
precacheAndRoute(self.__WB_MANIFEST)

// Firebase configuration
const firebaseConfig = {
  apiKey: 'AIzaSyAIK4xKoyDyUr_1plCvs-pbMgHVisyQtSg',
  authDomain: 'hireon-6e1f8.firebaseapp.com',
  projectId: 'hireon-6e1f8',
  storageBucket: 'hireon-6e1f8.firebasestorage.app',
  messagingSenderId: '277744446068',
  appId: '1:277744446068:web:2e55885ff0e9d137f6bf21',
  measurementId: 'G-NJNB9B90PP',
}

const app = initializeApp(firebaseConfig)
const messaging = getMessaging(app)

// Handle background messages
onBackgroundMessage(messaging, (payload) => {
  console.log('[SW] Background message received:', payload)

  const { title, body, icon } = payload.notification ?? {}
  const data = payload.data ?? {}

  let avatarUrl = data.sender_avatar || icon
  if (!avatarUrl || avatarUrl === '/favicon.svg') {
    const nameMatch = title?.match(/from\s+([^💬]+)/i)
    const name = nameMatch ? nameMatch[1].trim() : 'User'
    const encodedName = encodeURIComponent(name)
    avatarUrl = `https://ui-avatars.com/api/?name=${encodedName}&background=6c47ff&color=fff&size=128`
  } else if (avatarUrl.startsWith('/')) {
    avatarUrl = self.location.origin + avatarUrl
  }

  self.registration.showNotification(title ?? 'HireOn', {
    body: body ?? '',
    icon: avatarUrl,
    badge: '/favicon.svg',
    data: payload.data,
  })
})

// Handle notification click events (open or focus app window)
self.addEventListener('notificationclick', (event: any) => {
  event.notification.close()
  const urlToOpen = new URL(event.notification.data?.click_action || '/', self.location.origin).href

  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((windowClients: any[]) => {
      // Focus if window already open
      for (const client of windowClients) {
        if (client.url === urlToOpen && 'focus' in client) {
          return client.focus()
        }
      }
      // Otherwise open a new window
      if (self.clients.openWindow) {
        return self.clients.openWindow(urlToOpen)
      }
    })
  )
})
