/// <reference lib="webworker" />
import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching'
import { clientsClaim } from 'workbox-core'

declare const self: any

// injectManifest (a custom service worker, unlike the auto-wired generateSW
// strategy) needs this pair spelled out explicitly, or a newly deployed
// worker installs but sits waiting in the background — potentially
// indefinitely — while any tab left open from before the deploy keeps being
// served by the OLD worker's stale precached bundle. skipWaiting activates
// the new worker as soon as it finishes installing; clientsClaim then hands
// it control of already-open tabs immediately, instead of only new ones.
self.skipWaiting()
clientsClaim()

cleanupOutdatedCaches()

// Precache list generated by workbox
precacheAndRoute(self.__WB_MANIFEST)

// Notifications are shown only inside Hybent (the bell panel and in-app
// toasts). This worker used to show Firebase push notifications as OS pop-ups;
// that's gone, and any browser that allowed them earlier is unsubscribed here
// so no push can reach it. (The file keeps its old name: vite.config.ts builds
// the service worker from it.)
self.addEventListener('activate', (event: any) => {
  event.waitUntil(
    self.registration.pushManager
      ?.getSubscription()
      .then((subscription: any) => subscription?.unsubscribe())
      .catch(() => undefined)
  )
})
