import { toast } from 'react-hot-toast'
import { Copy, KeyRound } from 'lucide-react'

import { Button, Dialog } from '@/components/hb'

/**
 * Shows a one-time temporary password generated by the backend (client
 * onboarding, password reset). It is never retrievable again, so the operator
 * gets an explicit copy action and must dismiss it deliberately.
 */
export default function TempPasswordDialog({
  creds,
  onClose,
  title = 'Temporary password',
}: {
  creds: { email: string; temp_password: string } | null
  onClose: () => void
  title?: string
}) {
  const copy = async () => {
    if (!creds) return
    try {
      await navigator.clipboard.writeText(creds.temp_password)
      toast.success('Password copied')
    } catch {
      toast.error('Could not copy — select it manually.')
    }
  }

  return (
    <Dialog
      open={!!creds}
      onClose={onClose}
      title={title}
      description="Share this with the user over a secure channel. It will not be shown again."
      size="sm"
      closeOnOverlayClick={false}
      footer={
        <Button size="sm" onClick={onClose}>
          Done
        </Button>
      }
    >
      {creds && (
        <div className="space-y-hb-3">
          <p className="text-hb-sm text-hb-muted">{creds.email}</p>
          <div className="flex items-center gap-2 rounded-hb-md border border-hb-border bg-hb-surface-2 p-3">
            <KeyRound size={15} aria-hidden className="shrink-0 text-hb-cyan" />
            <code className="min-w-0 flex-1 select-all break-all font-mono text-hb-sm text-hb-text">
              {creds.temp_password}
            </code>
            <Button size="sm" variant="ghost" icon={<Copy size={14} />} onClick={copy}>
              Copy
            </Button>
          </div>
        </div>
      )}
    </Dialog>
  )
}
