"""
Job Description PDF generation using xhtml2pdf.
"""
import logging
from datetime import datetime

logger = logging.getLogger(__name__)

JD_HTML_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<style>
  @page {{ margin: 2.5cm 2.2cm; }}
  body {{ font-family: 'Helvetica', 'Arial', sans-serif; font-size: 11pt; color: #1a1a1a; line-height: 1.6; margin: 0; padding: 0; }}

  .header {{ margin-bottom: 25px; }}
  .job-title {{ font-size: 14pt; font-weight: bold; color: #1a1a1a; margin: 0 0 16px 0; }}
  .meta-info {{ font-size: 11pt; color: #1a1a1a; margin-bottom: 12px; font-weight: bold; }}
  .meta-label {{ color: #1a1a1a; display: inline-block; }}

  h2 {{ font-size: 11pt; font-weight: bold; color: #1a1a1a; margin: 24px 0 10px 0; }}
  
  .section {{ margin-bottom: 20px; }}
  .paragraph {{ margin: 0 0 12px 0; text-align: justify; }}
  
  ul {{ margin: 0 0 15px 18px; padding: 0; list-style-type: disc; }}
  li {{ margin-bottom: 6px; }}

  .footer {{ position: fixed; bottom: -1cm; left: 0; right: 0; text-align: center; font-size: 9pt; color: #9ca3af; border-top: 0.5pt solid #eee; padding-top: 5px; }}
</style>
</head>
<body>

  <div class="header">
    <div class="job-title">Job Position: {title}</div>
    <div class="meta-info">Experience: {experience}</div>
    <div class="meta-info">Location: {location}</div>
  </div>

  <div class="section">
    <h2>Job Description</h2>
    <div class="paragraph">{description}</div>
  </div>

  <div class="section">
    <h2>Key Responsibilities</h2>
    <ul>
      {responsibilities_html}
    </ul>
  </div>

  <div class="section">
    <h2>Required Qualifications &amp; Skills</h2>
    <ul>
      {requirements_html}
    </ul>
  </div>

  {good_to_have_section}

  <div class="footer">
    Generated by Hybent Hiring AI &bull; {date}
  </div>

</body>
</html>
"""

async def generate_jd_pdf(data: dict) -> bytes:
    """
    Convert JD data to PDF bytes using xhtml2pdf.
    """
    try:
        import io
        from xhtml2pdf import pisa

        # Prepare list HTML
        resps = data.get("key_responsibilities", [])
        res_html = "".join([f"<li>{r}</li>" for r in resps])
        
        reqs = data.get("required_qualifications_skills", [])
        req_html = "".join([f"<li>{r}</li>" for r in reqs])
        
        good_to_have = data.get("good_to_have", [])
        good_to_have_html = ""
        if good_to_have:
            gh_list = "".join([f"<li>{s}</li>" for s in good_to_have])
            good_to_have_html = f'<div class="section"><h2>Good to have</h2><ul>{gh_list}</ul></div>'

        html_content = JD_HTML_TEMPLATE.format(
            title=data.get("title", "N/A"),
            experience=data.get("experience", "N/A"),
            location=data.get("location", "N/A"),
            description=data.get("description", ""),
            responsibilities_html=res_html,
            requirements_html=req_html,
            good_to_have_section=good_to_have_html,
            date=datetime.now().strftime("%B %d, %Y")
        )

        buf = io.BytesIO()
        result = pisa.CreatePDF(html_content, dest=buf)
        
        if result.err:
            raise RuntimeError(f"xhtml2pdf error: {result.err}")
            
        return buf.getvalue()
    except Exception as e:
        logger.error(f"JD PDF generation failed: {e}")
        raise
