import type { ChatMessageItem } from './types'

export function generateTranscriptText(messages: ChatMessageItem[]): string {
  const dateStr = new Date().toLocaleDateString('en-US', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  })
  const timeStr = new Date().toLocaleTimeString('en-US', {
    hour: '2-digit',
    minute: '2-digit',
  })

  let transcript = `====================================================\n`
  transcript += `HYBENT AI - CONVERSATION TRANSCRIPT\n`
  transcript += `Date: ${dateStr} at ${timeStr}\n`
  transcript += `====================================================\n\n`

  messages.forEach((msg) => {
    const senderLabel = msg.sender === 'ai' ? 'Hybent AI' : 'User'
    transcript += `[${msg.timestamp}] ${senderLabel}:\n${msg.text}\n\n`
  })

  transcript += `----------------------------------------------------\n`
  transcript += `Generated by Hybent AI • https://hybent.com\n`
  transcript += `----------------------------------------------------\n`

  return transcript
}

export function generateTranscriptMarkdown(messages: ChatMessageItem[]): string {
  const dateStr = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  })

  let md = `# Hybent AI — Conversation Transcript\n\n`
  md += `**Date:** ${dateStr}  \n`
  md += `**Exported from:** [Hybent Website](https://hybent.com)\n\n`
  md += `---\n\n`

  messages.forEach((msg) => {
    const avatar = msg.sender === 'ai' ? '🤖 **Hybent AI**' : '👤 **User**'
    md += `### ${avatar} *(${msg.timestamp})*\n\n${msg.text}\n\n`
  })

  md += `---\n\n`
  md += `*Generated by Hybent AI*  \n`
  return md
}

export function downloadFile(content: string, filename: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}

export function exportAsTxt(messages: ChatMessageItem[]) {
  const content = generateTranscriptText(messages)
  const filename = `hybent-ai-chat-${Date.now()}.txt`
  downloadFile(content, filename, 'text/plain;charset=utf-8')
}

export function exportAsMarkdown(messages: ChatMessageItem[]) {
  const content = generateTranscriptMarkdown(messages)
  const filename = `hybent-ai-chat-${Date.now()}.md`
  downloadFile(content, filename, 'text/markdown;charset=utf-8')
}

export function exportAsPdf(messages: ChatMessageItem[]) {
  const dateStr = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  })

  const printWindow = window.open('', '_blank')
  if (!printWindow) return

  let html = `
    <!DOCTYPE html>
    <html>
      <head>
        <title>Hybent AI Conversation - ${dateStr}</title>
        <style>
          body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; padding: 40px; color: #1a1040; max-width: 800px; margin: 0 auto; line-height: 1.6; }
          .header { border-bottom: 2px solid #6c47ff; padding-bottom: 16px; margin-bottom: 24px; display: flex; justify-content: space-between; align-items: center; }
          .brand { font-size: 22px; font-weight: bold; color: #6c47ff; }
          .meta { font-size: 13px; color: #6b5f8a; }
          .msg { margin-bottom: 20px; padding: 14px 18px; border-radius: 12px; }
          .msg-ai { background: #f4f1ff; border-left: 4px solid #6c47ff; }
          .msg-user { background: #f0fdf4; border-left: 4px solid #10b981; }
          .sender { font-weight: bold; font-size: 13px; margin-bottom: 6px; display: flex; justify-content: space-between; color: #4527aa; }
          .text { font-size: 14px; white-space: pre-wrap; }
          .footer { border-top: 1px solid #e2e8f0; margin-top: 40px; padding-top: 16px; text-align: center; font-size: 12px; color: #94a3b8; }
        </style>
      </head>
      <body>
        <div class="header">
          <div class="brand">HYBENT AI</div>
          <div class="meta">Date: ${dateStr}</div>
        </div>
  `

  messages.forEach((msg) => {
    const isAi = msg.sender === 'ai'
    html += `
      <div class="msg ${isAi ? 'msg-ai' : 'msg-user'}">
        <div class="sender">
          <span>${isAi ? 'Hybent AI' : 'User'}</span>
          <span>${msg.timestamp}</span>
        </div>
        <div class="text">${escapeHtml(msg.text)}</div>
      </div>
    `
  })

  html += `
        <div class="footer">
          Generated by Hybent AI &bull; https://hybent.com
        </div>
        <script>
          window.onload = function() { window.print(); }
        </script>
      </body>
    </html>
  `

  printWindow.document.write(html)
  printWindow.document.close()
}

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;')
}

export function exportProposalAsPdf(proposal: any) {
  const printWindow = window.open('', '_blank')
  if (!printWindow) return

  const title = proposal.title || 'Technical Project Proposal'
  const summary = proposal.client_summary || {}
  const objective = proposal.project_objective || ''
  const costRange = proposal.estimated_cost_range || ''
  const timeline = proposal.estimated_timeline || ''
  const deliverables = proposal.deliverables || []
  const techStack = proposal.recommended_technologies || []
  const features = proposal.suggested_features || []
  const process = proposal.development_process || []
  const nextSteps = proposal.next_steps || []

  let html = `
    <!DOCTYPE html>
    <html>
      <head>
        <title>${escapeHtml(title)} - Hybent AI</title>
        <style>
          body { font-family: 'Segoe UI', Arial, sans-serif; padding: 40px; color: #1a1040; max-width: 850px; margin: 0 auto; line-height: 1.6; }
          .header { border-bottom: 3px solid #6c47ff; padding-bottom: 20px; margin-bottom: 30px; display: flex; justify-content: space-between; align-items: flex-start; }
          .brand { font-size: 26px; font-weight: bold; color: #6c47ff; tracking-tight: -0.5px; }
          .subbrand { font-size: 13px; color: #64748b; font-weight: normal; margin-top: 4px; }
          .proposal-title { font-size: 22px; font-weight: bold; color: #1e1b4b; margin-bottom: 24px; }
          .section { margin-bottom: 28px; }
          .section-title { font-size: 15px; font-weight: bold; color: #4338ca; border-bottom: 1px solid #e0e7ff; padding-bottom: 6px; margin-bottom: 12px; text-transform: uppercase; tracking: 0.5px; }
          .card-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 12px; margin-bottom: 16px; }
          .info-card { background: #f8fafc; padding: 12px 16px; border-radius: 8px; border: 1px solid #e2e8f0; font-size: 13px; }
          .info-card strong { color: #334155; }
          .highlight-box { background: #f5f3ff; border-left: 4px solid #6c47ff; padding: 16px; border-radius: 8px; font-size: 14px; margin-bottom: 20px; }
          ul { margin: 0; padding-left: 20px; }
          li { font-size: 13px; margin-bottom: 6px; color: #334155; }
          table { w-full: 100%; width: 100%; border-collapse: collapse; margin-top: 10px; font-size: 13px; }
          th, td { border: 1px solid #e2e8f0; padding: 10px 12px; text-align: left; }
          th { background: #f1f5f9; color: #334155; font-weight: bold; }
          .disclaimer { font-size: 11px; color: #94a3b8; font-style: italic; margin-top: 8px; }
          .footer { border-top: 1px solid #e2e8f0; margin-top: 50px; padding-top: 20px; text-align: center; font-size: 12px; color: #64748b; }
        </style>
      </head>
      <body>
        <div class="header">
          <div>
            <div class="brand">HYBENT CONSULTING</div>
            <div class="subbrand">Official AI Business Technical Proposal</div>
          </div>
          <div style="text-align: right; font-size: 12px; color: #64748b;">
            Date: ${escapeHtml(summary.proposal_date || '')}<br/>
            Ref: ${escapeHtml(proposal.proposal_id || '')}
          </div>
        </div>

        <div class="proposal-title">${escapeHtml(title)}</div>

        <!-- 1. Client Summary -->
        <div class="section">
          <div class="section-title">1. Client Summary</div>
          <div class="card-grid">
            <div class="info-card"><strong>Client Name:</strong> ${escapeHtml(summary.client_name || '')}</div>
            <div class="info-card"><strong>Company:</strong> ${escapeHtml(summary.company_name || '')}</div>
            <div class="info-card"><strong>Email:</strong> ${escapeHtml(summary.email || '')}</div>
            <div class="info-card"><strong>Prepared By:</strong> ${escapeHtml(summary.prepared_by || '')}</div>
          </div>
        </div>

        <!-- 2. Project Objective -->
        <div class="section">
          <div class="section-title">2. Project Objective</div>
          <div class="highlight-box">${escapeHtml(objective)}</div>
        </div>

        <!-- 3. Recommended Technologies -->
        <div class="section">
          <div class="section-title">3. Recommended Technology Stack</div>
          <table>
            <thead>
              <tr><th>Category</th><th>Technology Stack</th></tr>
            </thead>
            <tbody>
              ${techStack.map((t: any) => `<tr><td><strong>${escapeHtml(t.category)}</strong></td><td>${escapeHtml(t.tech)}</td></tr>`).join('')}
            </tbody>
          </table>
        </div>

        <!-- 4. Suggested Features -->
        <div class="section">
          <div class="section-title">4. Core Feature Specifications</div>
          <ul>
            ${features.map((f: string) => `<li>${escapeHtml(f)}</li>`).join('')}
          </ul>
        </div>

        <!-- 5. Estimated Timeline & 6. Cost Range -->
        <div class="section">
          <div class="section-title">5 & 6. Timeline & Commercial Scope</div>
          <div class="card-grid">
            <div class="info-card"><strong>Estimated Timeline:</strong> ${escapeHtml(timeline)}</div>
            <div class="info-card"><strong>Estimated Cost Range:</strong> ${escapeHtml(costRange)}</div>
          </div>
          <div class="disclaimer">*Note: Initial preliminary estimate subject to detailed discovery.*</div>
        </div>

        <!-- 7. Deliverables -->
        <div class="section">
          <div class="section-title">7. Key Deliverables</div>
          <ul>
            ${deliverables.map((d: string) => `<li>${escapeHtml(d)}</li>`).join('')}
          </ul>
        </div>

        <!-- 8. Development Process -->
        <div class="section">
          <div class="section-title">8. Agile Methodology</div>
          <ul>
            ${process.map((p: string) => `<li>${escapeHtml(p)}</li>`).join('')}
          </ul>
        </div>

        <!-- 9. Next Steps -->
        <div class="section">
          <div class="section-title">9. Next Steps</div>
          <ul>
            ${nextSteps.map((ns: string) => `<li>${escapeHtml(ns)}</li>`).join('')}
          </ul>
        </div>

        <div class="footer">
          Hybent Consulting &bull; https://hybent.com &bull; Confidential & Proprietary
        </div>
        <script>
          window.onload = function() { window.print(); }
        </script>
      </body>
    </html>
  `

  printWindow.document.write(html)
  printWindow.document.close()
}

export function exportDiscoveryReportAsPdf(report: any) {
  const printWindow = window.open('', '_blank')
  if (!printWindow) return

  const title = report.title || 'Project Discovery Report'
  const summary = report.executive_summary || ''
  const problems = report.business_problems || []
  const personas = report.target_user_personas || []
  const features = report.core_features || []
  const budget = report.budget_summary || ''
  const timeline = report.timeline_summary || ''
  const challenges = report.technical_challenges_and_mitigation || []
  const arch = report.recommended_architecture || {}
  const actionPlan = report.strategic_action_plan || []

  let html = `
    <!DOCTYPE html>
    <html>
      <head>
        <title>${escapeHtml(title)} - Hybent AI</title>
        <style>
          body { font-family: 'Segoe UI', Arial, sans-serif; padding: 40px; color: #1a1040; max-width: 850px; margin: 0 auto; line-height: 1.6; }
          .header { border-bottom: 3px solid #0d9488; padding-bottom: 20px; margin-bottom: 30px; display: flex; justify-content: space-between; align-items: flex-start; }
          .brand { font-size: 26px; font-weight: bold; color: #0d9488; tracking-tight: -0.5px; }
          .subbrand { font-size: 13px; color: #64748b; font-weight: normal; margin-top: 4px; }
          .report-title { font-size: 22px; font-weight: bold; color: #115e59; margin-bottom: 24px; }
          .section { margin-bottom: 28px; }
          .section-title { font-size: 15px; font-weight: bold; color: #0f766e; border-bottom: 1px solid #ccfbf1; padding-bottom: 6px; margin-bottom: 12px; text-transform: uppercase; tracking: 0.5px; }
          .highlight-box { background: #f0fdf4; border-left: 4px solid #0d9488; padding: 16px; border-radius: 8px; font-size: 14px; margin-bottom: 20px; }
          .card-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 12px; margin-bottom: 16px; }
          .info-card { background: #f8fafc; padding: 12px 16px; border-radius: 8px; border: 1px solid #e2e8f0; font-size: 13px; }
          .info-card strong { color: #334155; }
          ul { margin: 0; padding-left: 20px; }
          li { font-size: 13px; margin-bottom: 6px; color: #334155; }
          table { width: 100%; border-collapse: collapse; margin-top: 10px; font-size: 13px; }
          th, td { border: 1px solid #e2e8f0; padding: 10px 12px; text-align: left; }
          th { background: #f1f5f9; color: #334155; font-weight: bold; }
          .footer { border-top: 1px solid #e2e8f0; margin-top: 50px; padding-top: 20px; text-align: center; font-size: 12px; color: #64748b; }
        </style>
      </head>
      <body>
        <div class="header">
          <div>
            <div class="brand">HYBENT CONSULTING</div>
            <div class="subbrand">Official Project Discovery & Architecture Assessment</div>
          </div>
          <div style="text-align: right; font-size: 12px; color: #64748b;">
            Date: ${escapeHtml(report.generated_at || '')}<br/>
            Ref: ${escapeHtml(report.report_id || '')}
          </div>
        </div>

        <div class="report-title">${escapeHtml(title)}</div>

        <!-- 1. Executive Summary -->
        <div class="section">
          <div class="section-title">1. Executive Summary & Context</div>
          <div class="highlight-box">${escapeHtml(summary)}</div>
        </div>

        <!-- 2. Business Problems -->
        <div class="section">
          <div class="section-title">2. Identified Business Problems & Pain Points</div>
          <ul>
            ${problems.map((p: string) => `<li>${escapeHtml(p)}</li>`).join('')}
          </ul>
        </div>

        <!-- 3. Target User Personas -->
        <div class="section">
          <div class="section-title">3. Target User Personas & Roles</div>
          <table>
            <thead><tr><th>Role</th><th>Description</th></tr></thead>
            <tbody>
              ${personas.map((u: any) => `<tr><td><strong>${escapeHtml(u.role)}</strong></td><td>${escapeHtml(u.description)}</td></tr>`).join('')}
            </tbody>
          </table>
        </div>

        <!-- 4. Core Feature Specifications -->
        <div class="section">
          <div class="section-title">4. Core Feature Specifications</div>
          <ul>
            ${features.map((f: string) => `<li>${escapeHtml(f)}</li>`).join('')}
          </ul>
        </div>

        <!-- 5 & 6. Budget & Timeline -->
        <div class="section">
          <div class="section-title">5 & 6. Commercial Scope & Delivery Timeline</div>
          <div class="card-grid">
            <div class="info-card"><strong>Budget Summary:</strong> ${escapeHtml(budget)}</div>
            <div class="info-card"><strong>Delivery Timeline:</strong> ${escapeHtml(timeline)}</div>
          </div>
        </div>

        <!-- 7. Technical Challenges & Risk Mitigation -->
        <div class="section">
          <div class="section-title">7. Technical Challenges & Risk Mitigation</div>
          <table>
            <thead><tr><th>Identified Challenge</th><th>Mitigation Strategy</th></tr></thead>
            <tbody>
              ${challenges.map((c: any) => `<tr><td><strong>${escapeHtml(c.challenge)}</strong></td><td>${escapeHtml(c.mitigation)}</td></tr>`).join('')}
            </tbody>
          </table>
        </div>

        <!-- 8. Recommended Architecture -->
        <div class="section">
          <div class="section-title">8. Recommended Technology Stack</div>
          <div class="card-grid">
            <div class="info-card"><strong>Frontend:</strong> ${escapeHtml(arch.frontend || '')}</div>
            <div class="info-card"><strong>Backend API:</strong> ${escapeHtml(arch.backend || '')}</div>
            <div class="info-card"><strong>Database & Vector:</strong> ${escapeHtml(arch.database || '')}</div>
            <div class="info-card"><strong>Infrastructure:</strong> ${escapeHtml(arch.infrastructure || '')}</div>
          </div>
        </div>

        <!-- 9. Strategic Action Plan -->
        <div class="section">
          <div class="section-title">9. Strategic Action Plan</div>
          <ul>
            ${actionPlan.map((step: string) => `<li>${escapeHtml(step)}</li>`).join('')}
          </ul>
        </div>

        <div class="footer">
          Hybent AI Consulting &bull; https://hybent.com &bull; Confidential
        </div>
        <script>
          window.onload = function() { window.print(); }
        </script>
      </body>
    </html>
  `

  printWindow.document.write(html)
  printWindow.document.close()
}

export async function copyTranscriptToClipboard(messages: ChatMessageItem[]): Promise<boolean> {
  const content = generateTranscriptText(messages)
  try {
    await navigator.clipboard.writeText(content)
    return true
  } catch {
    return false
  }
}
