"""add_ai_credits_and_rules

Revision ID: 297b4d6e701f
Revises: 031_merge_heads
Create Date: 2026-07-16 13:17:30.971336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '297b4d6e701f'
down_revision: Union[str, None] = '031_merge_heads'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_credit_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('feature', sa.String(length=100), nullable=False),
    sa.Column('cost_type', sa.String(length=50), nullable=False),
    sa.Column('fixed_cost', sa.Integer(), nullable=False),
    sa.Column('token_input_cost_per_1k', sa.Float(), nullable=False),
    sa.Column('token_output_cost_per_1k', sa.Float(), nullable=False),
    sa.Column('audio_cost_per_second', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_credit_rules_feature'), 'ai_credit_rules', ['feature'], unique=True)
    op.create_table('organization_ai_credits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('allowed_credits', sa.Integer(), nullable=False),
    sa.Column('used_credits', sa.Integer(), nullable=False),
    sa.Column('reset_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('warning_50_sent', sa.Boolean(), nullable=False),
    sa.Column('warning_25_sent', sa.Boolean(), nullable=False),
    sa.Column('warning_10_sent', sa.Boolean(), nullable=False),
    sa.Column('warning_5_sent', sa.Boolean(), nullable=False),
    sa.Column('warning_0_sent', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_ai_credits_organization_id'), 'organization_ai_credits', ['organization_id'], unique=True)
    op.execute('DROP INDEX IF EXISTS ix_user_settings_user_id')
    op.drop_table('user_settings')
    op.add_column('ai_usage', sa.Column('credits_used', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('ai_usage', sa.Column('cost', sa.Float(), nullable=True))
    op.execute('DROP INDEX IF EXISTS ix_applications_candidate_created_at_desc')
    op.execute('DROP INDEX IF EXISTS ix_applications_candidate_job')
    op.execute('DROP INDEX IF EXISTS ix_applications_org_applied_at')
    op.execute('DROP INDEX IF EXISTS ix_applications_org_job_candidate')
    # Safely recreate FK with CASCADE (drop old constraint first if it exists)
    try:
        op.drop_constraint('applications_candidate_id_fkey', 'applications', type_='foreignkey')
    except Exception:
        pass
    op.create_foreign_key(None, 'applications', 'candidates', ['candidate_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.alter_column('candidates', 'import_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.execute('DROP INDEX IF EXISTS ix_candidates_current_company_trgm')
    op.execute('DROP INDEX IF EXISTS ix_candidates_current_title_trgm')
    op.execute('DROP INDEX IF EXISTS ix_candidates_email_trgm')
    op.execute('DROP INDEX IF EXISTS ix_candidates_full_name_trgm')
    op.execute('DROP INDEX IF EXISTS ix_candidates_org_applied_job_title')
    op.execute('DROP INDEX IF EXISTS ix_candidates_org_created_at')
    op.execute('DROP INDEX IF EXISTS ix_candidates_org_created_at_desc')
    op.execute('DROP INDEX IF EXISTS ix_candidates_org_created_by')
    op.execute('DROP INDEX IF EXISTS ix_candidates_org_match_score')
    op.execute('DROP INDEX IF EXISTS ix_candidates_org_match_score_desc')
    op.execute('DROP INDEX IF EXISTS ix_candidates_org_phone')
    op.execute('DROP INDEX IF EXISTS ix_candidates_org_pipeline_stage')
    op.execute('DROP INDEX IF EXISTS ix_candidates_resume_storage_path')
    op.execute('DROP INDEX IF EXISTS ix_candidates_skills_gin')
    op.execute('DROP INDEX IF EXISTS ix_candidates_tags_gin')
    op.create_index(op.f('ix_candidates_created_by_id'), 'candidates', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_candidates_pipeline_stage'), 'candidates', ['pipeline_stage'], unique=False)
    op.create_index(op.f('ix_candidates_user_id'), 'candidates', ['user_id'], unique=False)
    op.execute('DROP INDEX IF EXISTS ix_interview_panelists_user_id')
    op.execute('DROP INDEX IF EXISTS ix_interviews_candidate_scheduled_at_desc')
    op.execute('DROP INDEX IF EXISTS ix_interviews_org_scheduled_at')
    op.execute('DROP INDEX IF EXISTS ix_jobs_org_status_created_at_desc')
    op.execute('DROP INDEX IF EXISTS ix_jobs_org_status_display_order')
    op.create_index(op.f('ix_jobs_display_order'), 'jobs', ['display_order'], unique=False)
    op.execute('DROP INDEX IF EXISTS ix_notifications_user_unread')
    op.execute('DROP INDEX IF EXISTS ix_offers_application_id')
    op.execute('DROP INDEX IF EXISTS ix_offers_created_by')
    op.execute('DROP INDEX IF EXISTS ix_pre_screening_sessions_org_id')
    # Drop unique constraint safely
    try:
        op.drop_constraint('pre_screening_sessions_invite_token_key', 'pre_screening_sessions', type_='unique')
    except Exception:
        pass
    op.execute('DROP INDEX IF EXISTS ix_pre_screening_sessions_invite_token')
    op.create_index(op.f('ix_pre_screening_sessions_invite_token'), 'pre_screening_sessions', ['invite_token'], unique=True)
    op.create_index(op.f('ix_pre_screening_sessions_application_id'), 'pre_screening_sessions', ['application_id'], unique=False)
    op.create_index(op.f('ix_pre_screening_sessions_job_id'), 'pre_screening_sessions', ['job_id'], unique=False)
    op.create_index(op.f('ix_pre_screening_sessions_organization_id'), 'pre_screening_sessions', ['organization_id'], unique=False)
    op.execute('DROP INDEX IF EXISTS ix_scorecards_submitted_by')
    op.execute('DROP INDEX IF EXISTS uq_user_preferences_user_id')
    op.create_index(op.f('ix_user_preferences_user_id'), 'user_preferences', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_preferences_user_id'), table_name='user_preferences')
    op.create_index('uq_user_preferences_user_id', 'user_preferences', ['user_id'], unique=True)
    op.create_index('ix_scorecards_submitted_by', 'scorecards', ['submitted_by_id'], unique=False)
    op.drop_index(op.f('ix_pre_screening_sessions_organization_id'), table_name='pre_screening_sessions')
    op.drop_index(op.f('ix_pre_screening_sessions_job_id'), table_name='pre_screening_sessions')
    op.drop_index(op.f('ix_pre_screening_sessions_application_id'), table_name='pre_screening_sessions')
    op.drop_index(op.f('ix_pre_screening_sessions_invite_token'), table_name='pre_screening_sessions')
    op.create_index('ix_pre_screening_sessions_invite_token', 'pre_screening_sessions', ['invite_token'], unique=False)
    op.create_unique_constraint('pre_screening_sessions_invite_token_key', 'pre_screening_sessions', ['invite_token'])
    op.create_index('ix_pre_screening_sessions_org_id', 'pre_screening_sessions', ['organization_id'], unique=False)
    op.create_index('ix_offers_created_by', 'offers', ['created_by_id'], unique=False)
    op.create_index('ix_offers_application_id', 'offers', ['application_id'], unique=False)
    op.create_index('ix_notifications_user_unread', 'notifications', ['user_id', 'is_read', sa.literal_column('created_at DESC')], unique=False)
    op.drop_index(op.f('ix_jobs_display_order'), table_name='jobs')
    op.create_index('ix_jobs_org_status_display_order', 'jobs', ['organization_id', 'status', 'display_order'], unique=False)
    op.create_index('ix_jobs_org_status_created_at_desc', 'jobs', ['organization_id', 'status', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_interviews_org_scheduled_at', 'interviews', ['organization_id', 'scheduled_at'], unique=False)
    op.create_index('ix_interviews_candidate_scheduled_at_desc', 'interviews', ['candidate_id', sa.literal_column('scheduled_at DESC')], unique=False)
    op.create_index('ix_interview_panelists_user_id', 'interview_panelists', ['user_id'], unique=False)
    op.drop_index(op.f('ix_candidates_user_id'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_pipeline_stage'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_created_by_id'), table_name='candidates')
    op.create_index('ix_candidates_tags_gin', 'candidates', ['tags'], unique=False, postgresql_using='gin')
    op.create_index('ix_candidates_skills_gin', 'candidates', ['skills'], unique=False, postgresql_using='gin')
    op.create_index('ix_candidates_resume_storage_path', 'candidates', ['resume_storage_path'], unique=False, postgresql_where='(resume_storage_path IS NOT NULL)')
    op.create_index('ix_candidates_org_pipeline_stage', 'candidates', ['organization_id', 'pipeline_stage'], unique=False)
    op.create_index('ix_candidates_org_phone', 'candidates', ['organization_id', 'phone'], unique=False, postgresql_where='(phone IS NOT NULL)')
    op.create_index('ix_candidates_org_match_score_desc', 'candidates', ['organization_id', sa.literal_column('match_score DESC NULLS LAST')], unique=False)
    op.create_index('ix_candidates_org_match_score', 'candidates', ['organization_id', sa.literal_column('match_score DESC NULLS LAST')], unique=False)
    op.create_index('ix_candidates_org_created_by', 'candidates', ['organization_id', 'created_by_id'], unique=False)
    op.create_index('ix_candidates_org_created_at_desc', 'candidates', ['organization_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_candidates_org_created_at', 'candidates', ['organization_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_candidates_org_applied_job_title', 'candidates', ['organization_id', 'applied_job_title'], unique=False)
    op.create_index('ix_candidates_full_name_trgm', 'candidates', ['full_name'], unique=False, postgresql_using='gin')
    op.create_index('ix_candidates_email_trgm', 'candidates', ['email'], unique=False, postgresql_using='gin')
    op.create_index('ix_candidates_current_title_trgm', 'candidates', ['current_title'], unique=False, postgresql_using='gin')
    op.create_index('ix_candidates_current_company_trgm', 'candidates', ['current_company'], unique=False, postgresql_using='gin')
    op.alter_column('candidates', 'import_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'active'::character varying"))
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.create_foreign_key('applications_candidate_id_fkey', 'applications', 'candidates', ['candidate_id'], ['id'], ondelete='RESTRICT')
    op.create_index('ix_applications_org_job_candidate', 'applications', ['organization_id', 'job_id', 'candidate_id'], unique=False)
    op.create_index('ix_applications_org_applied_at', 'applications', ['organization_id', 'applied_at'], unique=False)
    op.create_index('ix_applications_candidate_job', 'applications', ['candidate_id', 'job_id'], unique=False)
    op.create_index('ix_applications_candidate_created_at_desc', 'applications', ['candidate_id', sa.literal_column('created_at DESC')], unique=False)
    op.drop_column('ai_usage', 'cost')
    op.drop_column('ai_usage', 'credits_used')
    op.create_table('user_settings',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_settings_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='user_settings_pkey')
    )
    op.create_index('ix_user_settings_user_id', 'user_settings', ['user_id'], unique=True)
    op.drop_index(op.f('ix_organization_ai_credits_organization_id'), table_name='organization_ai_credits')
    op.drop_table('organization_ai_credits')
    op.drop_index(op.f('ix_ai_credit_rules_feature'), table_name='ai_credit_rules')
    op.drop_table('ai_credit_rules')
    # ### end Alembic commands ###
